# Generated by Django 2.2 on 2022-04-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_products_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='active',
        ),
    ]
